/**
 * Aquatic Ecosystem Profiles — Utah Fishing Locations
 *
 * Comprehensive biological data for each of 18 fishing locations.
 * Used by LureRecommender and FlyRecommender to produce
 * biologically-informed, location-aware recommendations.
 *
 * Keys match FISHING_LOCATIONS in FishingMode.jsx.
 */

export const ECOSYSTEMS = {

  // ═══════════════════════════════════════════════════════════════════
  //  RIVERS
  // ═══════════════════════════════════════════════════════════════════

  'provo-river': {
    forage: {
      primary: [
        { name: 'Sculpin', size: '2-4"', peakMonths: [3,4,5,9,10,11], habitat: 'Rocky bottom runs', matchLure: ['Sculpin', 'Crawfish'], matchFly: ['streamer', 'buggerStill'] },
        { name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Rocky substrate, undercut banks', matchLure: ['Crawfish', 'Brown/Orange'], matchFly: ['streamer'] },
      ],
      secondary: [
        { name: 'Aquatic worms', size: 'Small', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Substrate', matchLure: [], matchFly: ['worm'] },
        { name: 'Scuds (Gammarus)', size: '#14-18', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Weed beds, spring creeks', matchLure: [], matchFly: ['scud'] },
      ],
    },
    hatches: {
      bwo:        { months: [3,4,5,9,10,11], intensity: 'heavy', peakHours: '1-4 PM', notes: 'Lower Provo is one of Utah\'s best BWO rivers — overcast days are epic' },
      pmd:        { months: [5,6,7], intensity: 'moderate', peakHours: '11 AM-2 PM', notes: 'PMDs emerge midday in riffles, especially below Deer Creek' },
      caddis:     { months: [5,6,7,8], intensity: 'heavy', peakHours: '4-8 PM', notes: 'Mother\'s Day caddis in May can be outstanding' },
      midge:      { months: [1,2,3,11,12], intensity: 'heavy', peakHours: '11 AM-2 PM', notes: 'Winter mainstay — tiny sizes #22-26 required' },
      stonefly:   { months: [4,5,6], intensity: 'moderate', peakHours: 'Morning', notes: 'Golden stones in upper sections, little black stones earlier' },
      trico:      { months: [7,8], intensity: 'low', peakHours: '7-9 AM', notes: 'Sparse but present on lower section calm mornings' },
      terrestrial:{ months: [6,7,8,9], intensity: 'moderate', peakHours: '1-5 PM', notes: 'Hoppers along grassy banks, ants under cottonwoods' },
    },
    waterClarity: { typical: 'clear', visibilityFt: { spring: 6, summer: 10, fall: 12, winter: 8 }, factors: 'Tailwater below Deer Creek stays clear year-round; upper sections can muddy during spring runoff mid-May to mid-June' },
    substrate: { primary: 'gravel', secondary: 'cobble and boulder', notes: 'Classic trout gravel riffles with cobble pools — ideal spawning habitat throughout' },
    thermocline: null,
    dissolvedOxygen: { summer: { epilimnion: null, metalimnion: null, hypolimnion: null }, notes: 'Moving water — well-oxygenated year-round from Deer Creek tailwater releases' },
    vegetation: { types: [{ name: 'Watercress', depth: '0-2 ft', season: 'year-round' }, { name: 'Elodea', depth: '1-4 ft', season: 'spring-fall' }], coverage: 'sparse' },
    invertebrates: { scuds: 'high', crayfish: 'moderate', leeches: 'low', snails: 'moderate', sowbugs: 'high' },
    predatorPrey: { topPredator: 'Brown Trout', preyChain: 'Invertebrates → Sculpin/Crayfish → Brown Trout', keyRelationship: 'Trophy browns feed primarily on sculpin and crayfish — match the hatch with olive/brown streamers' },
  },

  'middle-provo': {
    forage: { primary: [{ name: 'Sculpin', size: '2-3"', peakMonths: [3,4,5,9,10,11], habitat: 'Rocky runs below dam', matchLure: ['Sculpin', 'Brown'], matchFly: ['streamer'] }, { name: 'Scuds (Gammarus)', size: '#14-18', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Weed beds in meadow section', matchLure: [], matchFly: ['scud'] }], secondary: [{ name: 'Crayfish', size: '1-2"', peakMonths: [5,6,7,8,9], habitat: 'Rocky riffles', matchLure: ['Crawfish'], matchFly: ['streamer'] }] },
    hatches: { bwo: { months: [3,4,5,9,10,11], intensity: 'heavy', peakHours: '1-4 PM', notes: 'Jordanelle tailwater produces outstanding BWO — rivals lower Provo' }, pmd: { months: [5,6,7], intensity: 'moderate', peakHours: '11 AM-2 PM', notes: 'Meadow section PMDs are reliable' }, caddis: { months: [5,6,7,8], intensity: 'moderate', peakHours: '5-8 PM', notes: 'Evening caddis in meadow bends' }, midge: { months: [1,2,3,11,12], intensity: 'heavy', peakHours: '11 AM-1 PM', notes: 'Winter tailwater midging — dress warm' }, stonefly: { months: [4,5,6], intensity: 'low', peakHours: 'Morning', notes: 'Less prominent than lower Provo' }, damselfly: { months: [6,7], intensity: 'low', peakHours: 'Midday', notes: 'Slow meadow pools have some damsel activity' }, terrestrial: { months: [6,7,8,9], intensity: 'moderate', peakHours: '1-5 PM', notes: 'Hopper-dropper along Midway meadow stretch' } },
    waterClarity: { typical: 'clear', visibilityFt: { spring: 8, summer: 12, fall: 10, winter: 8 }, factors: 'Jordanelle dam release keeps water cold and clear; meadow section stays clear unless construction/development runoff' },
    substrate: { primary: 'gravel', secondary: 'silt in meadow bends', notes: 'Tailwater gravel near dam transitions to finer substrate in meadow section' },
    thermocline: null,
    dissolvedOxygen: { summer: null, notes: 'Cold tailwater from Jordanelle hypolimnion — excellent DO year-round' },
    vegetation: { types: [{ name: 'Elodea', depth: '1-3 ft', season: 'spring-fall' }, { name: 'Watercress', depth: '0-2 ft', season: 'year-round' }], coverage: 'moderate' },
    invertebrates: { scuds: 'high', crayfish: 'low', leeches: 'low', snails: 'moderate', sowbugs: 'high' },
    predatorPrey: { topPredator: 'Brown Trout', preyChain: 'Scuds/Insects → Whitefish → Brown Trout', keyRelationship: 'Scud-rich meadow water grows big fish — pink/orange scud patterns are year-round producers' },
  },

  'weber-river': {
    forage: { primary: [{ name: 'Crayfish', size: '2-4"', peakMonths: [5,6,7,8,9], habitat: 'Under rocks throughout river', matchLure: ['Crawfish', 'Brown/Orange'], matchFly: ['streamer'] }, { name: 'Sculpin', size: '2-3"', peakMonths: [3,4,5,9,10,11], habitat: 'Rocky runs and pools', matchLure: ['Sculpin'], matchFly: ['streamer'] }], secondary: [{ name: 'Chub', size: '3-5"', peakMonths: [5,6,7,8,9], habitat: 'Pools and eddies', matchLure: ['Natural Minnow', 'Silver'], matchFly: ['streamer'] }] },
    hatches: { bwo: { months: [3,4,5,9,10,11], intensity: 'moderate', peakHours: '1-4 PM', notes: 'Good BWO below Rockport, less prolific than Provo' }, caddis: { months: [5,6,7,8], intensity: 'heavy', peakHours: '5-9 PM', notes: 'Weber is a caddis river — evening hatches can be blizzards' }, stonefly: { months: [4,5,6], intensity: 'heavy', peakHours: 'Morning', notes: 'Golden stoneflies in upper reaches — big attractor dry flies work' }, midge: { months: [1,2,3,11,12], intensity: 'moderate', peakHours: '11 AM-1 PM', notes: 'Winter midges below Rockport tailwater' }, terrestrial: { months: [6,7,8,9], intensity: 'heavy', peakHours: '12-5 PM', notes: 'Grassy banks from Peoa to Coalville are hopper heaven — BEST hopper water in the state' } },
    waterClarity: { typical: 'clear', visibilityFt: { spring: 4, summer: 8, fall: 10, winter: 6 }, factors: 'More freestone character than Provo — spring runoff (May-June) significantly reduces clarity. Below Rockport stays clearer.' },
    substrate: { primary: 'cobble', secondary: 'gravel and boulder', notes: 'Larger cobble and boulder than Provo — classic freestone substrate with deep undercut banks' },
    thermocline: null,
    dissolvedOxygen: { summer: null, notes: 'Freestone river — good DO from riffles and rapids, warmer than tailwater rivers in summer' },
    vegetation: { types: [{ name: 'Riparian grass', depth: 'Bank', season: 'spring-fall' }], coverage: 'sparse' },
    invertebrates: { scuds: 'low', crayfish: 'high', leeches: 'moderate', snails: 'low', sowbugs: 'low' },
    predatorPrey: { topPredator: 'Brown Trout', preyChain: 'Caddis/Stoneflies → Crayfish/Sculpin → Brown Trout', keyRelationship: 'Crayfish-dominant ecosystem — craw-colored streamers and jigs outproduce everything for trophy browns' },
  },

  'green-river': {
    forage: { primary: [{ name: 'Scuds (Hyalella)', size: '#14-18', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Weed beds and rocky substrate throughout', matchLure: [], matchFly: ['scud'] }, { name: 'Cicadas', size: '#4-8', peakMonths: [6], habitat: 'Cottonwood-lined banks A & B sections', matchLure: [], matchFly: ['cicada'] }], secondary: [{ name: 'Sculpin', size: '2-4"', peakMonths: [3,4,5,9,10,11], habitat: 'Rocky bottom throughout', matchLure: ['Sculpin'], matchFly: ['streamer'] }, { name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Under boulders', matchLure: ['Crawfish'], matchFly: ['streamer'] }] },
    hatches: { bwo: { months: [3,4,5,9,10,11], intensity: 'heavy', peakHours: '1-4 PM', notes: 'World-class BWO — thick hatches on overcast spring/fall days' }, pmd: { months: [5,6,7], intensity: 'heavy', peakHours: '10 AM-2 PM', notes: 'Green River PMD hatch is legendary — match size precisely (#16-18)' }, caddis: { months: [5,6,7,8], intensity: 'moderate', peakHours: '5-8 PM', notes: 'Caddis supplement PMDs in the evening' }, cicada: { months: [6], intensity: 'heavy', peakHours: 'All day', notes: 'LEGENDARY June cicada hatch — trophy browns eat them on the surface. Plan your trip around this.' }, midge: { months: [1,2,3,11,12], intensity: 'heavy', peakHours: '11 AM-2 PM', notes: 'Year-round midge production from cold tailwater — #22-26 essential' }, trico: { months: [7,8], intensity: 'moderate', peakHours: '7-10 AM', notes: 'Trico spinner falls on calm mornings — tiny flies, big rewards' }, terrestrial: { months: [7,8,9], intensity: 'moderate', peakHours: '12-5 PM', notes: 'Hoppers along cottonwood sections — not as dominant as Weber but effective' } },
    waterClarity: { typical: 'clear', visibilityFt: { spring: 15, summer: 20, fall: 18, winter: 12 }, factors: 'Flaming Gorge dam releases from the hypolimnion produce gin-clear, cold water. Among the clearest rivers in the West. Long leaders (12-15 ft) required.' },
    substrate: { primary: 'cobble', secondary: 'gravel and weed beds', notes: 'Mixed cobble/gravel with extensive aquatic weed beds (Elodea, Chara) that harbor massive scud populations' },
    thermocline: null,
    dissolvedOxygen: { summer: null, notes: 'Cold hypolimnetic release from Flaming Gorge — 46-52°F year-round with excellent DO' },
    vegetation: { types: [{ name: 'Elodea', depth: '1-6 ft', season: 'year-round' }, { name: 'Chara', depth: '2-8 ft', season: 'year-round' }, { name: 'Cladophora', depth: '1-4 ft', season: 'summer' }], coverage: 'dense' },
    invertebrates: { scuds: 'extreme', crayfish: 'moderate', leeches: 'low', snails: 'high', sowbugs: 'high' },
    predatorPrey: { topPredator: 'Brown Trout', preyChain: 'Scuds/Insects → Sculpin → Rainbow/Brown Trout', keyRelationship: 'Scud-driven ecosystem — fish grow fat on year-round scuds. Orange/pink scud patterns are ALWAYS productive. June cicadas override everything.' },
  },

  'strawberry': { forage: { primary: [{ name: 'Utah Chub', size: '3-6"', peakMonths: [5,6,7,8,9], habitat: 'Weed beds 10-20 ft', matchLure: ['Natural Minnow', 'Silver', 'Perch'], matchFly: ['streamer', 'buggerStill'] }, { name: 'Chironomid larvae', size: '#14-18', peakMonths: [4,5,6,9,10], habitat: 'Mud/silt bottom throughout', matchLure: [], matchFly: ['chironomid'] }], secondary: [{ name: 'Scuds', size: '#16-18', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Weed beds', matchLure: [], matchFly: ['scud'] }, { name: 'Damselfly nymphs', size: '#10-12', peakMonths: [6,7,8], habitat: 'Submerged vegetation', matchLure: [], matchFly: ['damsel'] }] }, hatches: { chironomid: { months: [4,5,6,9,10], intensity: 'heavy', peakHours: '10 AM-2 PM', notes: 'Chironomids are THE hatch at Strawberry — indicator fishing at exact depth is deadly' }, callibaetis: { months: [6,7,8], intensity: 'moderate', peakHours: '11 AM-3 PM', notes: 'Calm sunny days bring callibaetis spinners — fish rise in shallow bays' }, damselfly: { months: [6,7], intensity: 'heavy', peakHours: 'Morning', notes: 'Damsel migration in June/July — strip nymphs toward shore through weed beds' } }, waterClarity: { typical: 'clear', visibilityFt: { spring: 8, summer: 12, fall: 10, winter: 6 }, factors: 'High-elevation reservoir stays relatively clear. Algae bloom can reduce visibility in late summer.' }, substrate: { primary: 'mud', secondary: 'gravel at inlets, rocky points', notes: 'Soft mud bottom supports massive chironomid populations — key to the fishery' }, thermocline: { spring: { depth: [10, 20], tempRange: [45, 55] }, summer: { depth: [20, 35], tempRange: [55, 65] }, fall: { depth: [15, 25], tempRange: [50, 58] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'High (8-10 mg/L)', metalimnion: 'Moderate (5-7 mg/L)', hypolimnion: 'Low (2-4 mg/L)' }, notes: 'Summer DO squeeze pushes trout to thermocline depth — key for trolling strategy' }, vegetation: { types: [{ name: 'Chara (stonewort)', depth: '5-15 ft', season: 'spring-fall' }, { name: 'Potamogeton (pondweed)', depth: '5-20 ft', season: 'summer' }, { name: 'Myriophyllum (milfoil)', depth: '3-12 ft', season: 'summer' }], coverage: 'dense' }, invertebrates: { scuds: 'high', crayfish: 'none', leeches: 'moderate', snails: 'high', sowbugs: 'moderate' }, predatorPrey: { topPredator: 'Cutthroat Trout', preyChain: 'Chironomids/Scuds → Chub → Cutthroat', keyRelationship: 'Utah chub are the primary forage for large cutthroat — chub-colored tube jigs and swimbaits match the predator-prey dynamic perfectly' } },

  'scofield': { forage: { primary: [{ name: 'Chironomid larvae', size: '#14-18', peakMonths: [4,5,6,9,10], habitat: 'Soft bottom throughout', matchLure: [], matchFly: ['chironomid'] }, { name: 'Utah Chub', size: '2-4"', peakMonths: [5,6,7,8,9], habitat: 'Weed beds', matchLure: ['Natural Minnow'], matchFly: ['streamer', 'buggerStill'] }], secondary: [{ name: 'Scuds', size: '#16-18', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Dense vegetation', matchLure: [], matchFly: ['scud'] }, { name: 'Callibaetis nymphs', size: '#14-16', peakMonths: [6,7,8], habitat: 'Weed beds near surface', matchLure: [], matchFly: ['callibaetis'] }] }, hatches: { chironomid: { months: [4,5,6,9,10], intensity: 'extreme', peakHours: '10 AM-3 PM', notes: 'Scofield has the heaviest chironomid hatches in Utah — chromie under indicator is THE method' }, callibaetis: { months: [6,7,8], intensity: 'heavy', peakHours: '11 AM-3 PM', notes: 'Outstanding callibaetis — fish rising everywhere on calm sunny afternoons' }, damselfly: { months: [6,7], intensity: 'heavy', peakHours: '10 AM-1 PM', notes: 'Strong damsel migration through extensive weed beds' } }, waterClarity: { typical: 'clear', visibilityFt: { spring: 6, summer: 10, fall: 8, winter: 5 }, factors: 'High-elevation Blue Ribbon water. Can get algae bloom in late summer reducing clarity.' }, substrate: { primary: 'mud', secondary: 'silt with organic matter', notes: 'Nutrient-rich soft bottom drives the incredible chironomid/callibaetis production' }, thermocline: { spring: { depth: [8, 15], tempRange: [42, 52] }, summer: { depth: [15, 25], tempRange: [55, 62] }, fall: { depth: [10, 20], tempRange: [48, 56] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'High (8-10 mg/L)', metalimnion: 'Moderate (5-7 mg/L)', hypolimnion: 'Low (2-4 mg/L)' }, notes: 'Similar DO profile to Strawberry — trout hold at thermocline in summer' }, vegetation: { types: [{ name: 'Potamogeton (pondweed)', depth: '3-15 ft', season: 'summer' }, { name: 'Chara', depth: '5-12 ft', season: 'spring-fall' }, { name: 'Myriophyllum (milfoil)', depth: '3-10 ft', season: 'summer' }], coverage: 'dense' }, invertebrates: { scuds: 'high', crayfish: 'none', leeches: 'moderate', snails: 'high', sowbugs: 'moderate' }, predatorPrey: { topPredator: 'Cutthroat Trout', preyChain: 'Chironomids/Callibaetis → Chub → Cutthroat/Tiger Trout', keyRelationship: 'Chironomid-driven ecosystem — fish that learn to indicator-nymph chironomids at Scofield will consistently outfish everyone else' } },

  'deer-creek': { forage: { primary: [{ name: 'Threadfin Shad', size: '2-4"', peakMonths: [5,6,7,8,9,10], habitat: 'Open water schools', matchLure: ['Shad', 'Silver', 'Chrome'], matchFly: ['streamer'] }, { name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Rocky points and dam face', matchLure: ['Crawfish', 'Brown/Orange'], matchFly: ['streamer'] }], secondary: [{ name: 'Yellow Perch (juvenile)', size: '2-3"', peakMonths: [6,7,8,9], habitat: 'Weed beds in coves', matchLure: ['Perch', 'Chartreuse/Green'], matchFly: ['streamer'] }, { name: 'Chironomid larvae', size: '#16-20', peakMonths: [4,5,9,10], habitat: 'Soft bottom areas', matchLure: [], matchFly: ['chironomid'] }] }, hatches: { chironomid: { months: [4,5,9,10], intensity: 'moderate', peakHours: '11 AM-2 PM', notes: 'Moderate chironomid activity — not as heavy as Strawberry but indicator nymphing works' }, callibaetis: { months: [6,7,8], intensity: 'low', peakHours: 'Midday', notes: 'Some callibaetis in sheltered coves' }, damselfly: { months: [6,7], intensity: 'moderate', peakHours: 'Morning', notes: 'Damsel nymphs in Wallsburg Bay weed beds' } }, waterClarity: { typical: 'stained', visibilityFt: { spring: 4, summer: 6, fall: 5, winter: 4 }, factors: 'Provo River inflow brings sediment. Stained water favors walleye (light-sensitive eyes) — this is why Deer Creek is Utah\'s best walleye fishery.' }, substrate: { primary: 'mixed', secondary: 'rocky dam face, mud in coves, gravel at inlets', notes: 'Diverse substrate supports the multi-species fishery — walleye on rock, bass in soft-bottom coves' }, thermocline: { spring: { depth: [12, 22], tempRange: [48, 58] }, summer: { depth: [18, 30], tempRange: [60, 70] }, fall: { depth: [15, 25], tempRange: [55, 63] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'High (7-9 mg/L)', metalimnion: 'Moderate (4-6 mg/L)', hypolimnion: 'Low (1-3 mg/L)' }, notes: 'Summer DO crash in deep water — walleye and bass hold at thermocline.' }, vegetation: { types: [{ name: 'Potamogeton', depth: '5-15 ft', season: 'summer' }, { name: 'Cattails', depth: '0-3 ft', season: 'spring-fall' }], coverage: 'moderate' }, invertebrates: { scuds: 'low', crayfish: 'high', leeches: 'moderate', snails: 'moderate', sowbugs: 'low' }, predatorPrey: { topPredator: 'Walleye', preyChain: 'Shad/Perch → Walleye/Brown Trout', keyRelationship: 'Shad are the keystone forage — everything from walleye to browns keys on them. Match the hatch with silver/shad-colored presentations.' } },

  'jordanelle': { forage: { primary: [{ name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Rocky points, submerged roadbeds', matchLure: ['Crawfish', 'Brown/Orange', 'Green Pumpkin'], matchFly: ['streamer'] }, { name: 'Yellow Perch (juvenile)', size: '2-3"', peakMonths: [6,7,8,9], habitat: 'Standing timber, weed edges', matchLure: ['Perch', 'Chartreuse'], matchFly: ['streamer'] }], secondary: [{ name: 'Sculpin', size: '2-3"', peakMonths: [3,4,5,9,10,11], habitat: 'Rocky substrate', matchLure: ['Sculpin'], matchFly: ['streamer'] }] }, hatches: { chironomid: { months: [4,5,6], intensity: 'moderate', peakHours: '10 AM-1 PM', notes: 'Moderate chironomid activity post ice-off' }, damselfly: { months: [6,7], intensity: 'moderate', peakHours: '10 AM-12 PM', notes: 'Damsel migration along weed edges in Rock Cliff area' }, callibaetis: { months: [6,7,8], intensity: 'low', peakHours: 'Midday', notes: 'Limited callibaetis — not a primary driver here' } }, waterClarity: { typical: 'clear', visibilityFt: { spring: 6, summer: 12, fall: 10, winter: 8 }, factors: 'Rocky reservoir with good clarity most of the year.' }, substrate: { primary: 'rock', secondary: 'gravel and submerged roadbeds', notes: 'Rocky substrate is why this is Utah\'s best smallmouth fishery — crayfish thrive on rock' }, thermocline: { spring: { depth: [10, 18], tempRange: [48, 56] }, summer: { depth: [18, 30], tempRange: [58, 68] }, fall: { depth: [12, 22], tempRange: [52, 62] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'High (8-10 mg/L)', metalimnion: 'Moderate (5-7 mg/L)', hypolimnion: 'Low (2-4 mg/L)' }, notes: 'Good summer DO in upper water column — smallmouth stay active on rocky structure' }, vegetation: { types: [{ name: 'Potamogeton', depth: '5-12 ft', season: 'summer' }], coverage: 'sparse' }, invertebrates: { scuds: 'low', crayfish: 'high', leeches: 'low', snails: 'moderate', sowbugs: 'low' }, predatorPrey: { topPredator: 'Smallmouth Bass', preyChain: 'Crayfish/Perch → Smallmouth Bass', keyRelationship: 'Crayfish are 60%+ of smallmouth diet here — craw-colored soft plastics (green pumpkin, PB&J) are mandatory' } },

  'starvation': { forage: { primary: [{ name: 'Yellow Perch (juvenile)', size: '2-4"', peakMonths: [5,6,7,8,9], habitat: 'Weed edges and old river channel', matchLure: ['Perch', 'Chartreuse'], matchFly: [] }, { name: 'Utah Chub', size: '3-5"', peakMonths: [5,6,7,8,9], habitat: 'Schools in open water', matchLure: ['Natural Minnow', 'Silver'], matchFly: ['streamer'] }], secondary: [{ name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Rocky points', matchLure: ['Crawfish'], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'stained', visibilityFt: { spring: 3, summer: 5, fall: 4, winter: 3 }, factors: 'Duchesne River inflow carries sediment. Naturally stained — benefits walleye.' }, substrate: { primary: 'rock', secondary: 'mud in river channel', notes: 'Rocky points are key walleye structure — old Duchesne River channel holds fish in summer' }, thermocline: { spring: { depth: [10, 20], tempRange: [44, 52] }, summer: { depth: [20, 35], tempRange: [58, 68] }, fall: { depth: [15, 28], tempRange: [50, 60] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'Moderate (6-8 mg/L)', metalimnion: 'Low (3-5 mg/L)', hypolimnion: 'Very low (1-2 mg/L)' }, notes: 'Summer DO limitations push walleye to 15-30 ft zone' }, vegetation: { types: [{ name: 'Sparse pondweed', depth: '5-10 ft', season: 'summer' }], coverage: 'sparse' }, invertebrates: { scuds: 'low', crayfish: 'moderate', leeches: 'low', snails: 'low', sowbugs: 'low' }, predatorPrey: { topPredator: 'Walleye', preyChain: 'Perch/Chub → Walleye', keyRelationship: 'Perch are primary walleye forage — perch-colored jigs and crankbaits are top producers' } },

  'flaming-gorge': { forage: { primary: [{ name: 'Kokanee Salmon', size: '6-12"', peakMonths: [5,6,7,8,9], habitat: 'Open water following thermocline', matchLure: ['Silver', 'Kokanee Pattern'], matchFly: [] }, { name: 'Crayfish', size: '2-4"', peakMonths: [5,6,7,8,9], habitat: 'Rocky shorelines and shoals', matchLure: ['Crawfish', 'Brown/Orange'], matchFly: [] }], secondary: [{ name: 'Utah Chub', size: '4-8"', peakMonths: [5,6,7,8,9], habitat: 'Near-shore schools', matchLure: ['Natural Minnow'], matchFly: [] }, { name: 'Sculpin', size: '3-5"', peakMonths: [3,4,5,9,10,11], habitat: 'Rocky bottom in canyon', matchLure: ['Sculpin'], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'clear', visibilityFt: { spring: 15, summer: 25, fall: 20, winter: 15 }, factors: 'Extremely clear impoundment in red-rock canyon. Visibility often exceeds 20 ft in summer.' }, substrate: { primary: 'rock', secondary: 'underwater cliffs and canyon walls', notes: 'Deep rocky canyon structure defines the fishery — ledges, humps, and canyon walls are the key structural features' }, thermocline: { spring: { depth: [20, 40], tempRange: [42, 52] }, summer: { depth: [40, 60], tempRange: [52, 62] }, fall: { depth: [30, 50], tempRange: [48, 58] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'High (8-10 mg/L)', metalimnion: 'Moderate (5-7 mg/L)', hypolimnion: 'Moderate (4-6 mg/L)' }, notes: 'Deep clear reservoir maintains reasonable DO at depth — lake trout can access 100+ ft' }, vegetation: { types: [], coverage: 'sparse' }, invertebrates: { scuds: 'low', crayfish: 'high', leeches: 'low', snails: 'moderate', sowbugs: 'low' }, predatorPrey: { topPredator: 'Lake Trout', preyChain: 'Crayfish → Kokanee → Lake Trout', keyRelationship: 'Kokanee are the primary forage for trophy lake trout. Lakers follow kokanee schools seasonally — match depth and forage size with 4-6" spoons and jigs.' } },

  'bear-lake': { forage: { primary: [{ name: 'Bonneville Cisco', size: '3-6"', peakMonths: [1,5,6,7,8], habitat: 'Pelagic — open deep water', matchLure: ['Silver', 'White'], matchFly: [] }, { name: 'Bonneville Whitefish', size: '4-8"', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Deep water benthos', matchLure: ['Silver', 'White'], matchFly: [] }], secondary: [{ name: 'Bear Lake Sculpin', size: '2-3"', peakMonths: [3,4,5,9,10,11], habitat: 'Rocky bottom', matchLure: ['Sculpin'], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'clear', visibilityFt: { spring: 20, summer: 30, fall: 25, winter: 20 }, factors: 'Bear Lake is one of the clearest lakes in North America — 30+ ft visibility is normal.' }, substrate: { primary: 'rock', secondary: 'gravel and marl (calcium carbonate deposits)', notes: 'Unique marl bottom in deeper areas — rocky shoreline structure on east side' }, thermocline: { spring: { depth: [15, 30], tempRange: [38, 48] }, summer: { depth: [30, 60], tempRange: [48, 58] }, fall: { depth: [20, 45], tempRange: [42, 52] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'High (8-10 mg/L)', metalimnion: 'Moderate (6-8 mg/L)', hypolimnion: 'Moderate (5-7 mg/L)' }, notes: 'Deep cold water with good DO throughout — supports endemic deep-water species year-round' }, vegetation: { types: [], coverage: 'sparse' }, invertebrates: { scuds: 'moderate', crayfish: 'low', leeches: 'low', snails: 'high', sowbugs: 'low' }, predatorPrey: { topPredator: 'Lake Trout', preyChain: 'Cisco/Whitefish → Cutthroat/Lake Trout', keyRelationship: 'Endemic Bonneville Cisco are the primary forage — found NOWHERE ELSE ON EARTH. January cisco runs are Utah\'s most unique fishing tradition.' } },

  'lake-powell': { forage: { primary: [{ name: 'Threadfin Shad', size: '2-4"', peakMonths: [4,5,6,7,8,9,10,11], habitat: 'Pelagic schools, canyon narrows', matchLure: ['Shad', 'Silver', 'Chrome', 'White'], matchFly: [] }, { name: 'Gizzard Shad', size: '4-8"', peakMonths: [5,6,7,8,9,10], habitat: 'Open water, back of canyons', matchLure: ['Large Shad', 'Silver'], matchFly: [] }], secondary: [{ name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Canyon walls and brush piles', matchLure: ['Crawfish'], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'clear', visibilityFt: { spring: 10, summer: 15, fall: 12, winter: 10 }, factors: 'Canyon reservoir — clarity varies by arm. Main channel clearest.' }, substrate: { primary: 'sandstone', secondary: 'canyon walls, submerged brush', notes: 'Unique red sandstone substrate and underwater canyon walls create striper habitat unlike any other water' }, thermocline: { spring: { depth: [20, 35], tempRange: [55, 65] }, summer: { depth: [30, 50], tempRange: [70, 80] }, fall: { depth: [20, 40], tempRange: [60, 72] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'High (7-9 mg/L)', metalimnion: 'Moderate (4-6 mg/L)', hypolimnion: 'Low (1-3 mg/L)' }, notes: 'Warm desert reservoir — summer DO crash at depth forces stripers into narrow thermal/DO band' }, vegetation: { types: [], coverage: 'sparse' }, invertebrates: { scuds: 'none', crayfish: 'moderate', leeches: 'low', snails: 'low', sowbugs: 'none' }, predatorPrey: { topPredator: 'Striped Bass', preyChain: 'Threadfin Shad → Striped Bass/Largemouth Bass', keyRelationship: 'Threadfin shad are EVERYTHING at Powell. The entire fishery revolves around the shad — follow the shad, find the fish. Silver/white lures mandatory.' } },

  'utah-lake': { forage: { primary: [{ name: 'Common Carp (juvenile)', size: '2-6"', peakMonths: [5,6,7,8,9], habitat: 'Shallow flats, river mouths', matchLure: ['Gold', 'Brown'], matchFly: [] }, { name: 'Gizzard Shad', size: '3-6"', peakMonths: [5,6,7,8,9,10], habitat: 'Open water schools', matchLure: ['Shad', 'Silver', 'Chrome'], matchFly: [] }], secondary: [{ name: 'Utah Sucker', size: '4-8"', peakMonths: [4,5,6], habitat: 'River mouths and shallows', matchLure: ['Gold', 'Natural'], matchFly: [] }, { name: 'Aquatic worms', size: 'Small', peakMonths: [1,2,3,4,5,6,7,8,9,10,11,12], habitat: 'Mud bottom', matchLure: [], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'turbid', visibilityFt: { spring: 1, summer: 2, fall: 2, winter: 1 }, factors: 'Utah Lake is naturally turbid — max 14 ft deep, wind easily stirs fine sediment. THIS IS AN ADVANTAGE for catfish, walleye, and white bass.' }, substrate: { primary: 'mud', secondary: 'silt and fine sediment', notes: 'Soft mud bottom throughout — rip-rap along marinas and dikes provides the only hard structure' }, thermocline: { spring: null, summer: null, fall: null, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'Moderate (5-7 mg/L)', metalimnion: null, hypolimnion: null }, notes: 'Shallow lake — no thermocline. Wind mixing keeps DO moderate.' }, vegetation: { types: [{ name: 'Cattails', depth: '0-3 ft', season: 'spring-fall' }, { name: 'Hardstem bulrush', depth: '1-5 ft', season: 'spring-fall' }], coverage: 'moderate' }, invertebrates: { scuds: 'none', crayfish: 'low', leeches: 'moderate', snails: 'moderate', sowbugs: 'none' }, predatorPrey: { topPredator: 'Channel Catfish', preyChain: 'Carp/Shad/Suckers → Catfish/Walleye/White Bass', keyRelationship: 'Turbid warm water is a bait-fishing paradise. Stink travels far in murky water — cut bait and stink bait dominate for catfish.' } },

  'pineview': { forage: { primary: [{ name: 'Yellow Perch', size: '3-5"', peakMonths: [5,6,7,8,9], habitat: 'Weed beds and docks', matchLure: ['Perch', 'Firetiger', 'Chartreuse'], matchFly: [] }, { name: 'Utah Chub', size: '3-6"', peakMonths: [5,6,7,8,9], habitat: 'Schools in open water and weed edges', matchLure: ['Natural Minnow', 'Silver'], matchFly: [] }], secondary: [{ name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Rocky areas', matchLure: ['Crawfish'], matchFly: [] }, { name: 'Bluegill (juvenile)', size: '1-2"', peakMonths: [6,7,8], habitat: 'Shallow coves', matchLure: ['Bluegill'], matchFly: [] }] }, hatches: { damselfly: { months: [6,7], intensity: 'moderate', peakHours: 'Morning', notes: 'Damsel nymphs in extensive weed beds' }, callibaetis: { months: [6,7,8], intensity: 'low', peakHours: 'Midday', notes: 'Some callibaetis near weed beds' } }, waterClarity: { typical: 'stained', visibilityFt: { spring: 4, summer: 6, fall: 5, winter: 4 }, factors: 'Productive warm-water reservoir — algae in summer reduces clarity. Stained water benefits tiger muskie.' }, substrate: { primary: 'mud', secondary: 'gravel at inlets', notes: 'Soft bottom with extensive weed beds — the dense vegetation is why tiger muskie and bass thrive here' }, thermocline: { spring: { depth: [8, 15], tempRange: [50, 58] }, summer: { depth: [15, 25], tempRange: [65, 75] }, fall: { depth: [10, 18], tempRange: [55, 65] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'Moderate (6-8 mg/L)', metalimnion: 'Low (3-5 mg/L)', hypolimnion: 'Very low (1-2 mg/L)' }, notes: 'DO crash below thermocline pushes all predators to weed-edge zone 5-25 ft' }, vegetation: { types: [{ name: 'Eurasian milfoil', depth: '3-15 ft', season: 'spring-fall' }, { name: 'Curly-leaf pondweed', depth: '3-12 ft', season: 'spring-summer' }, { name: 'Cattails', depth: '0-3 ft', season: 'spring-fall' }], coverage: 'dense' }, invertebrates: { scuds: 'low', crayfish: 'moderate', leeches: 'moderate', snails: 'moderate', sowbugs: 'low' }, predatorPrey: { topPredator: 'Tiger Muskie', preyChain: 'Perch/Chub/Bluegill → Largemouth Bass/Tiger Muskie', keyRelationship: 'Tiger muskie ambush from dense weed edges — large perch and chub-colored swimbaits 6-10" along vegetation transitions are the ticket' } },

  'willard-bay': { forage: { primary: [{ name: 'Gizzard Shad', size: '3-8"', peakMonths: [4,5,6,7,8,9,10,11], habitat: 'Pelagic schools throughout', matchLure: ['Shad', 'Silver', 'Chrome', 'White'], matchFly: [] }], secondary: [{ name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Rip-rap dikes', matchLure: ['Crawfish'], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'stained', visibilityFt: { spring: 3, summer: 4, fall: 3, winter: 3 }, factors: 'Dike reservoir fed by Weber River — naturally stained. Stained water drives aggressive wiper/walleye feeding.' }, substrate: { primary: 'mud', secondary: 'rip-rap dikes', notes: 'Soft bottom with engineered rip-rap dikes providing the only hard structure' }, thermocline: { spring: null, summer: { depth: [8, 15], tempRange: [68, 78] }, fall: null, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'Moderate (5-7 mg/L)', metalimnion: null, hypolimnion: null }, notes: 'Relatively shallow — wind mixing prevents severe DO stratification.' }, vegetation: { types: [{ name: 'Cattails (marina areas)', depth: '0-3 ft', season: 'spring-fall' }], coverage: 'sparse' }, invertebrates: { scuds: 'none', crayfish: 'moderate', leeches: 'low', snails: 'low', sowbugs: 'none' }, predatorPrey: { topPredator: 'Wiper', preyChain: 'Gizzard Shad → Wiper/Walleye/Catfish', keyRelationship: 'Gizzard shad are the entire food chain. When wipers push shad to the surface, it creates explosive surface-feeding events. Silver spoons and white swimbaits — ALWAYS.' } },

  'yuba': { forage: { primary: [{ name: 'Utah Chub', size: '3-6"', peakMonths: [4,5,6,7,8,9,10], habitat: 'Schools in weed beds and open water', matchLure: ['Natural Minnow', 'Silver', 'Perch'], matchFly: [] }], secondary: [{ name: 'Yellow Perch (juvenile)', size: '2-3"', peakMonths: [6,7,8,9], habitat: 'Weed beds', matchLure: ['Perch', 'Chartreuse'], matchFly: [] }, { name: 'Crayfish', size: '2-3"', peakMonths: [5,6,7,8,9], habitat: 'Rocky points', matchLure: ['Crawfish'], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'stained', visibilityFt: { spring: 3, summer: 5, fall: 4, winter: 3 }, factors: 'Wind-exposed 22-mile reservoir — waves stir bottom sediment frequently. Stained water benefits pike and muskie.' }, substrate: { primary: 'mud', secondary: 'rock points and gravel', notes: 'Extensive shallow weed beds on mud bottom — northern pike and tiger muskie ambush from vegetation edges' }, thermocline: { spring: { depth: [8, 15], tempRange: [44, 54] }, summer: { depth: [15, 30], tempRange: [60, 72] }, fall: { depth: [10, 20], tempRange: [52, 62] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'Moderate (6-8 mg/L)', metalimnion: 'Low (3-5 mg/L)', hypolimnion: 'Very low (1-2 mg/L)' }, notes: 'Warm productive water — pike and muskie hold at weed-edge thermocline zone' }, vegetation: { types: [{ name: 'Curly-leaf pondweed', depth: '3-12 ft', season: 'spring-summer' }, { name: 'Sago pondweed', depth: '3-10 ft', season: 'summer' }, { name: 'Cattails', depth: '0-3 ft', season: 'spring-fall' }], coverage: 'dense' }, invertebrates: { scuds: 'low', crayfish: 'moderate', leeches: 'moderate', snails: 'moderate', sowbugs: 'low' }, predatorPrey: { topPredator: 'Northern Pike', preyChain: 'Chub/Perch → Walleye/Wiper/Pike/Tiger Muskie', keyRelationship: 'Predator paradise — four apex predators competing for chub and perch. Large chub-colored swimbaits and spinnerbaits along weed transitions produce the biggest fish.' } },

  'sand-hollow': { forage: { primary: [{ name: 'Bluegill (juvenile)', size: '1-3"', peakMonths: [5,6,7,8,9,10], habitat: 'Sandy flats and red-rock ledges', matchLure: ['Bluegill', 'Green/Orange'], matchFly: [] }], secondary: [{ name: 'Crayfish', size: '1-2"', peakMonths: [3,4,5,6,7,8,9,10,11], habitat: 'Red rock ledges and sandy areas', matchLure: ['Crawfish', 'Brown/Red'], matchFly: [] }] }, hatches: {}, waterClarity: { typical: 'clear', visibilityFt: { spring: 10, summer: 15, fall: 12, winter: 10 }, factors: 'Desert reservoir with red sandstone substrate — very clear water year-round. Light line and natural colors essential.' }, substrate: { primary: 'sandstone', secondary: 'sand flats', notes: 'Unique red sandstone ledges create bass habitat unlike any other Utah water — sight fishing possible year-round' }, thermocline: { spring: { depth: [8, 15], tempRange: [55, 65] }, summer: { depth: [15, 25], tempRange: [72, 82] }, fall: { depth: [10, 18], tempRange: [62, 72] }, winter: null }, dissolvedOxygen: { summer: { epilimnion: 'Moderate (6-8 mg/L)', metalimnion: 'Low (3-5 mg/L)', hypolimnion: 'Low (2-4 mg/L)' }, notes: 'Warm desert reservoir — bass move to 15-25 ft in summer heat' }, vegetation: { types: [], coverage: 'sparse' }, invertebrates: { scuds: 'none', crayfish: 'moderate', leeches: 'low', snails: 'low', sowbugs: 'none' }, predatorPrey: { topPredator: 'Largemouth Bass', preyChain: 'Bluegill/Crayfish → Largemouth Bass', keyRelationship: 'Classic warm-water bass ecosystem — bluegill are primary forage. Bluegill-colored jigs and swimbaits around red rock ledges are money.' } },
};

// Segment aliases — new segment IDs resolve to the same ecosystem data
ECOSYSTEMS['provo-lower']  = ECOSYSTEMS['provo-river'];
ECOSYSTEMS['provo-middle'] = ECOSYSTEMS['middle-provo'];
ECOSYSTEMS['provo-upper']  = ECOSYSTEMS['provo-river'];
ECOSYSTEMS['green-a']      = ECOSYSTEMS['green-river'];
ECOSYSTEMS['green-b']      = ECOSYSTEMS['green-river'];
ECOSYSTEMS['green-c']      = ECOSYSTEMS['green-river'];

export function getEcosystem(locationId) {
  return ECOSYSTEMS[locationId] || null;
}

export function getWaterClarity(locationId, season) {
  const eco = ECOSYSTEMS[locationId];
  if (!eco?.waterClarity) return { clarity: 'unknown', visibilityFt: null };
  const vis = eco.waterClarity.visibilityFt?.[season] || null;
  return { clarity: eco.waterClarity.typical, visibilityFt: vis, factors: eco.waterClarity.factors };
}

export function getThermocline(locationId, season) {
  const eco = ECOSYSTEMS[locationId];
  return eco?.thermocline?.[season] || null;
}

export function getPrimaryForage(locationId) {
  const eco = ECOSYSTEMS[locationId];
  if (!eco?.forage?.primary) return [];
  return eco.forage.primary.map(f => f.name);
}

export function getForageColors(locationId) {
  const eco = ECOSYSTEMS[locationId];
  if (!eco?.forage) return [];
  const colors = new Set();
  [...(eco.forage.primary || []), ...(eco.forage.secondary || [])].forEach(f => {
    (f.matchLure || []).forEach(c => colors.add(c));
  });
  return [...colors];
}

export function getForageFlyKeys(locationId) {
  const eco = ECOSYSTEMS[locationId];
  if (!eco?.forage) return [];
  const keys = new Set();
  [...(eco.forage.primary || []), ...(eco.forage.secondary || [])].forEach(f => {
    (f.matchFly || []).forEach(k => keys.add(k));
  });
  return [...keys];
}

export function getActiveHatch(locationId, hatchKey, month) {
  const eco = ECOSYSTEMS[locationId];
  const hatch = eco?.hatches?.[hatchKey];
  if (!hatch) return null;
  if (hatch.months.includes(month)) return hatch;
  return null;
}

export function getActiveHatches(locationId, month) {
  const eco = ECOSYSTEMS[locationId];
  if (!eco?.hatches) return [];
  return Object.entries(eco.hatches)
    .filter(([, h]) => h.months.includes(month))
    .map(([key, data]) => ({ key, ...data }));
}
